language: java
jdk:
  - openjdk8
before_install:
  - chmod +x mvnw
  #- chmod +x scripts/deploy.sh

install: true
script:
  - ./mvnw clean package
  #- bash <(curl -s https://codecov.io/bash)

before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  overwrite: true

  file:
    - target/testprivate-$project_version.jar
    s
  skip_cleanup: true
  on:
    repo: dimpon/happycube
    tags: true
  name: $project_version

cache:
  directories:
    - $HOME/.m2
