language: java
jdk:
  - openjdk8
before_install:
  - chmod +x mvnw
  #- chmod +x scripts/deploy.sh

install: true
script:
  - ./mvnw clean package
  #- bash <(curl -s https://codecov.io/bash)

before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
  - git config --local user.name $GITHUB_USERNAME
  - git config --local user.email $GITHUB_EMAIL
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  overwrite: true

  file:
    - target/testprivate-$project_version.jar

  skip_cleanup: true
  on:
    repo: dimpon/testprivate
    tags: false
    condition: $TRAVIS_COMMIT_MESSAGE =~ ^(release)$
  name: $project_version

cache:
  directories:
    - $HOME/.m2
