sudo: false
language: java
jdk:
  - openjdk8

before_install:
  - chmod +x mvnw
  - gpg --version
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import --no-tty --batch
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust


before_script:
  - chmod +x mvnw

install: ./mvnw --settings .travis/settings.xml package -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

#script: ./mvnw clean deploy --settings .travis/settings.xml -DskipTests=true -B -U -Prelease

script: echo "script is skipped"

cache:
  directories:
    - $HOME/.m2

before_deploy:
  #- git config --local user.name $GITHUB_USERNAME
  #- git config --local user.email $GITHUB_EMAIL

  #- ./mvnw -B release:clean release:prepare -DskipTests=true -DupdateWorkingCopyVersions=false --settings .travis/settings.xml
  #- ./mvnw help:evaluate -N -Dexpression=project.version|grep -v '\['
  #- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
  - git stash
  - git checkout -f $TRAVIS_BRANCH
  - chmod +x mvnw
  - chmod +x scripts/deploy.sh
  #- ./mvnw -B release:prepare -DskipTests=true -DupdateWorkingCopyVersions=false --settings .travis/settings.xml
  - ./mvnw help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
  #- git checkout -f $TRAVIS_BRANC
  #- git config --local user.name $GITHUB_USERNAME
  #- git config --local user.email $GITHUB_EMAIL
  #- ./mvnw -B release:prepare -DskipTests=true -DupdateWorkingCopyVersions=false --settings .travis/settings.xm
  #- ./mvnw help:evaluate -N -Dexpression=project.version|grep -v '\['
  #- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

  #- export TRAVIS_TAG=${TRAVIS_TAG:-$project_version}
  #- git tag $TRAVIS_TAG
  #- echo $TRAVIS_TAG
  #- git tag $TRAVIS_TAG


deploy:

  - provider: script
  #script: scripts/deploy.sh
    script: ./mvnw release:prepare --settings .travis/settings.xml -DskipTests=true -B -U
  #./mvnw release:prepare release:perform --settings .travis/settings.xml -DskipTests=true -B -U -Prelease
  #provider: releases
  #api_key: $GITHUB_OAUTH_TOKEN
  #overwrite: true
  #file:
  #  - target/testprivate-$project_version.jar
  #  - target/testprivate-$project_version-javadoc.jar
  #  - target/testprivate-$project_version-sources.jar

    skip_cleanup: true
    on:
      repo: dimpon/testprivate
      tags: false
      condition: $TRAVIS_COMMIT_MESSAGE =~ ^(release)$
    name: "release"


  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    overwrite: true
    file:
      - target/testprivate-$project_version.jar
      - target/testprivate-$project_version-javadoc.jar
      - target/testprivate-$project_version-sources.jar
    skip_cleanup: true
      on:
        repo: dimpon/testprivate
        tags: true
      name: $project_version-github

  - provider: script
    script: ./mvnw deploy --settings .travis/settings.xml -DskipTests=true -B -U -Prelease

    skip_cleanup: true
      on:
        repo: dimpon/testprivate
        tags: true
      name: $project_version-sonatype


#deploy:
#  provider: script
#  script: .travis/release.sh
#  skip_cleanup: true
#  on:
#    repo: dimpon/testprivate
#    tags: true
#    jdk: openjdk8