sudo: false
language: java
jdk:
  - openjdk8
before_install:
  - chmod +x mvnw
before_script:
  - chmod +x mvnw
script: ./mvnw clean verify
cache:
  directories:
    - $HOME/.m2
before_deploy:
  - chmod +x mvnw
  - chmod +x .travis/release.sh
deploy:
  provider: script
  script: .travis/release.sh
  skip_cleanup: true
  on:
    repo: dimpon/testprivate
    tags: true
    jdk: openjdk8