sudo: false
language: java
jdk:
  - openjdk8

#integration with codecov, call webhook
after_success:
  - bash <(curl -s https://codecov.io/bash)

#import gpg keys and ownertrust for gpg signature
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import --no-tty --batch
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

#skipping install
install: echo "install..."

#that's what is run for every commit
script: ./mvnw clean test jacoco:report -e -B

#class not found issue when cache is enabled
#cache:
#  directories:
#    - $HOME/.m2

#save current version from pom
before_deploy:
  - echo "before_deploy..."
  - ./mvnw help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

deploy:

#change version to release, set a tag, increment version to the next snapshot TODO do not build project, just change and commit pom.xml
  - provider: script
    script: echo "launch release..." && git checkout -f $TRAVIS_BRANCH && ./mvnw release:prepare --settings .travis/settings.xml -Dmaven.test.skip=true -DskipTests -B -U
    skip_cleanup: false
    on:
      repo: dimpon/testprivate
      tags: false
      condition: $TRAVIS_COMMIT_MESSAGE =~ ^(release)$
      name: "launch release"

# deploy to sonatype
  - provider: script
    script: ./mvnw clean deploy --settings .travis/settings.xml -Dmaven.test.skip=true  -DskipTests -B -U -Prelease
    skip_cleanup: true
    on:
      repo: dimpon/testprivate
      tags: true
      name: "deploy to sonatype"

# deploy to github releases
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    overwrite: true
    file:
      - target/testprivate-$project_version.jar
      - target/testprivate-$project_version-javadoc.jar
      - target/testprivate-$project_version-sources.jar

    skip_cleanup: true
    on:
      repo: dimpon/testprivate
      tags: true
      name: $project_version
