language: java
jdk:
  - openjdk8
before_install:
  - chmod +x mvnw
  #- chmod +x scripts/deploy.sh

install: true
script:
  - ./mvnw clean package
  #- bash <(curl -s https://codecov.io/bash)

#before_deploy:
#  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
#  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    repo: dimpon/testprivate
    #type: push
    #commit_message: 'release'
    tags: true
    all_branches: true
    #condition: $COMMIT_MESSAGE = 'release'

cache:
  directories:
    - $HOME/.m2
